In [ ]:
! pip install xgboost

In [3]:
from utils.load_data import load_data

In [2]:
from build_baseline_model import main

In [3]:
output = main(False)

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/fsspec/registry.py:275: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)

In [1]:
from build_smoothed_model import main, smoothed_inference

In [6]:
trainers = main(False)
trainers.head(2)

/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)

Warning: Too many trainers to plot. Showing a random sample of 10.
Warning: Too many trainers to plot. Showing a random sample of 10.
Warning: Too many trainers to plot. Showing a random sample of 10.
Warning: Too many trainers to plot. Showing a random sample of 10.
Warning: Too many trainers to plot. Showing a random sample of 10.

,trainer_id,trainer_name,n_horses,n_entries,n_starts,dnf,scratched,vet_scratched,badly_beaten,breakdown,...,vet_scratched_pct,badly_beaten_pct,breakdown_pct,dnf_pct_smoothed,scratched_pct_smoothed,vet_scratched_pct_smoothed,badly_beaten_pct_smoothed,breakdown_pct_smoothed,baseline_prediction,actual
0,0,unknown trainer,2420,2703,8,0,2695,69,0,0,...,0.025527,0.000000,0.0,0.006776,0.983355,0.026021,0.025201,0.001642,276.619415,93.419928
1,5,Ronald B. Abrams,79,931,761,3,170,39,13,0,...,0.041890,0.017083,0.0,0.004911,0.179451,0.041420,0.018394,0.001018,94.398170,76.066769

In [4]:
df = load_data(False, False)
df = df[df['race_date'] >= '2023-01-01']
trainers = smoothed_inference(df, "2023")

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/fsspec/registry.py:275: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)
/home/ec2-user/SageMaker/hisa-trainer-injury/src/utils/load_data.py:16: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_yr = pd.read_csv(data_location)

In [5]:
trainers

,trainer_id,trainer_name,n_horses,n_entries,n_starts,dnf,scratched,vet_scratched,badly_beaten,breakdown,...,breakdown_pct,dnf_pct_smoothed,scratched_pct_smoothed,vet_scratched_pct_smoothed,badly_beaten_pct_smoothed,breakdown_pct_smoothed,baseline_prediction,actual,inj_above_avg,inj_above_avg_per_start
0,0,unknown trainer,222,237,2,0,235,11,0,0,...,0.0,0.006887,0.857905,0.043537,0.026472,0.001650,24.582241,14.893032,-9.689209,-4.844605
1,5,Ronald B. Abrams,8,37,33,1,4,2,2,0,...,0.0,0.008856,0.109263,0.041615,0.034335,0.001609,4.371143,7.206825,2.835682,0.085930
2,7,D. Kelly Ackerman,1,11,11,0,0,0,0,0,...,0.0,0.006723,0.087543,0.034338,0.024610,0.001638,0.897191,0.000000,-0.897191,-0.081563
3,22,Paul G. Aguirre,14,38,36,1,2,1,0,0,...,0.0,0.008790,0.083018,0.034814,0.020589,0.001605,3.937508,3.062285,-0.875223,-0.024312
4,32,Edward T. Allard,27,131,110,1,21,8,5,0,...,0.0,0.007425,0.148078,0.050098,0.035904,0.001516,12.705189,19.516239,6.811050,0.061919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2802,961333,Ernesto Ochoa,10,40,38,0,2,1,3,0,...,0.0,0.006274,0.081002,0.034365,0.039679,0.001603,3.840773,5.539854,1.699081,0.044713
2803,961370,Jose D'Angelo,235,870,746,2,124,75,9,0,...,0.0,0.004079,0.141031,0.080527,0.014079,0.001025,85.097733,117.517972,32.420239,0.043459
2804,961519,Don Roberson,3,27,25,1,2,1,0,0,...,0.0,0.009037,0.096182,0.037507,0.022184,0.001619,2.644016,3.062285,0.418269,0.016731
2805,961595,Michelle Elliott,47,259,222,0,37,8,9,0,...,0.0,0.004312,0.138276,0.032959,0.035841,0.001398,26.429340,23.389122,-3.040218,-0.013695
2806,961894,Alejandro Murillo Rodriguez,23,118,112,0,6,5,1,0,...,0.0,0.005303,0.066547,0.040024,0.018123,0.001514,12.650442,8.164874,-4.485568,-0.040050